---

- name: "SCORED | 5.7 | PATCH | Ensure access to the su command is restricted"
  block:
      - name: "SCORED | 5.7 | PATCH | Ensure access to the su command is restricted | Setting pm_wheel to use_uid"
        lineinfile:
            state: present
            dest: /etc/pam.d/su
            regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
            line: 'auth           required        pam_wheel.so use_uid {% if rhel8cis_sugroup is defined %}group={{ rhel8cis_sugroup }}{% endif %}'

      - name: "SCORED | 5.7 | PATCH | Ensure access to the su command is restricted | wheel group contains root"
        user:
            name: "{{ rhel8cis_sugroup_users }}"
            groups: "{{ rhel8cis_sugroup | default('wheel') }}"
  when:
      - rhel8cis_rule_5_7
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.7