---

- name: "SCORED | 5.5.1.1 | PATCH | Ensure password expiration is 365 days or less"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_MAX_DAYS'
      line: "PASS_MAX_DAYS {{ rhel8cis_pass['max_days'] }}"
  when:
      - rhel8cis_rule_5_5_1_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.5.1.1

- name: "SCORED | 5.5.1.2 | PATCH | Ensure minimum days between password changes is 7 or more"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_MIN_DAYS'
      line: "PASS_MIN_DAYS {{ rhel8cis_pass['min_days'] }}"
  when:
      - rhel8cis_rule_5_5_1_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.5.1.2

- name: "SCORED | 5.5.1.3 | PATCH | Ensure password expiration warning days is 7 or more"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_WARN_AGE'
      line: "PASS_WARN_AGE {{ rhel8cis_pass['warn_age'] }}"
  when:
      - rhel8cis_rule_5_5_1_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.5.1.3

- name: "SCORED | 5.5.1.4 | PATCH | Ensure inactive password lock is 30 days or less"
  block:
      - name: "SCORED | 5.5.1.4 | AUDIT | Ensure inactive password lock is 30 days or less | Check current settings"
        shell: useradd -D | grep INACTIVE={{ rhel8cis_inactivelock.lock_days }} | cut -f2 -d=
        changed_when: false
        failed_when: false
        register: rhel8cis_5_5_1_4_inactive_settings

      - name: "SCORED | 5.5.1.4 | PATCH | Ensure inactive password lock is 30 days or less | Set default inactive setting"
        command: useradd -D -f {{ rhel8cis_inactivelock.lock_days }}
        when: rhel8cis_5_5_1_4_inactive_settings.stdout == ""

      - name: "AUDIT | 5.5.1.4 | PATCH | Ensure inactive password lock is 30 days or less | Getting user list"
        shell: 'egrep ^[^:]+:[^\!*] /etc/shadow | cut -d: -f1'
        register: rhel_08_5_5_1_4_audit
        changed_when: false

      - name: "SCORED | 5.5.1.4 | PATCH | Ensure inactive password lock is 30 days or less | Apply Inactive setting to existing accounts"
        command: chage --inactive {{ rhel8cis_inactivelock.lock_days }} "{{ item }}"
        with_items:
            - "{{ rhel_08_5_5_1_4_audit.stdout_lines }}"
  when:
      - rhel8cis_rule_5_5_1_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.5.1.4

- name: "SCORED | 5.5.1.5 | PATCH | Ensure all users last password change date is in the past"
  block:
      - name: "SCORED | 5.5.1.5 | AUDIT | Ensure all users last password change date is in the past | Get current date in Unix Time"
        shell: echo $(($(date --utc --date "$1" +%s)/86400))
        failed_when: false
        changed_when: false
        register: rhel8cis_5_5_1_5_currentUT

      - name: "SCORED | 5.5.1.5 | AUDIT | Ensure all users last password change date is in the past | Get list of users with last changed pw date in the future"
        shell: "cat /etc/shadow | awk -F: '{if($3>{{ rhel8cis_5_5_1_5_currentUT.stdout }})print$1}'"
        changed_when: false
        failed_when: false
        register: rhel8cis_5_5_1_5_user_list

      - name: "SCORED | 5.5.1.5 | AUDIT | Ensure all users last password change date is in the past | Alert no pw change in the future exist"
        debug:
            msg: "Good News! All accounts have PW change dates that are in the past"
        when: rhel8cis_5_5_1_5_user_list.stdout == ""

      - name: "SCORED | 5.5.1.5 | AUDIT | Ensure all users last password change date is in the past | Alert on accounts with pw change in the future"
        debug:
            msg: "Warning! The following accounts have the last PW change date in the future: {{ rhel8cis_5_5_1_5_user_list.stdout_lines }}"
        when:
            - rhel8cis_5_5_1_5_user_list.stdout != ""
            - not rhel8cis_futurepwchgdate_autofix

      - name: "SCORED | 5.5.1.5 | PATCH | Ensure all users last password change date is in the past | Fix accounts with pw change in the future"
        command: passwd --expire {{ item }}
        when:
            - rhel8cis_5_5_1_5_user_list != ""
            - rhel8cis_futurepwchgdate_autofix
        with_items:
            - "{{ rhel8cis_5_5_1_5_user_list.stdout_lines }}"
  when:
      - rhel8cis_rule_5_5_1_5
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.5.1.5