---

- name: "SECTION | 5.1 | Configure time-based job schedulers"
  include_tasks: cis_5.1.x.yml

- name: "SECTION | 5.2 | Configure SSH Server"
  include_tasks: cis_5.2.x.yml

- name: "SECTION | 5.3 | Configure Profiles"
  import_tasks: cis_5.3.x.yml
  when:
  - rhel8cis_use_authconfig

- name: "SECTION | 5.4 | Configure PAM "
  include_tasks: cis_5.4.x.yml

- name: "SECTION | 5.5.1.x | Passwords and Accounts"
  include_tasks: cis_5.5.1.x.yml

- name: "SECTION | 5.5.x | System Accounts and User Settings"
  include_tasks: cis_5.5.x.yml

- name: "SECTION | 5.6 | Root Login"
  include_tasks: cis_5.6.yml

- name: Section | 5.7 | su Command Restriction
  include_tasks: cis_5.7.yml