---

- name: "3.4.1.1 | L1 | Ensure a Firewall package is installed"
  package:
      name: "{{ rhel8cis_firewall }}"
      state: present
  when:
      - rhel8cis_rule_3_4_1_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.1.1
