---

- name: "SECTION | 3.1.x | Disable unused network protocols and devices"
  import_tasks: cis_3.1.x.yml
# - name: "SECTION | 3.1.x | Packet and IP redirection"
#   import_tasks: cis_3.1.x.yml

- name: "SECTION | 3.2.x | Network Parameters (Host Only)"
  import_tasks: cis_3.2.x.yml

- name: "SECTION | 3.3.x | Network Parameters (Host and Router)"
  import_tasks: cis_3.3.x.yml

# - name: "SECTION | 3.3.x | Uncommon Network Protocols"
#   import_tasks: cis_3.3.x.yml

- name: "SECTION | 3.4.1.x | Configure firewalld"
  import_tasks: cis_3.4.1.1.yml
  when:
      - rhel8cis_firewall == "firewalld"

# - name: "SECTION | 3.4.1.x | firewall defined"
#   import_tasks: cis_3.4.1.1.yml

- name: "SECTION | 3.4.2.x | Configure nftables"
  include_tasks: cis_3.4.2.x.yml
  when:
  - rhel8cis_firewall == "nftables"

# - name: "SECTION | 3.4.2.x | firewalld firewall"
#   include_tasks: cis_3.4.2.x.yml
#   when:
#   - rhel8cis_firewall == "firewalld"

- name: "SECTION | 3.4.3.1.x | Configure iptables software"
  include_tasks: cis_3.4.3.1.x.yml
  when:
  - rhel8cis_firewall == "iptables"

- name: "SECTION | 3.4.3.2.x | Configure IPv4 iptables"
  include_tasks: cis_3.4.3.2.x.yml
  when:
  - rhel8cis_firewall == "iptables"

# - name: "SECTION | 3.4.3.x | Configure nftables firewall"
#   include_tasks: cis_3.4.3.x.yml
#   when:
#   - rhel8cis_firewall == "nftables"

# - name: "SECTION | 3.4.4.1.x | Configure iptables IPv4"
#   include_tasks: cis_3.4.4.1.x.yml
#   when:
#   - rhel8cis_firewall == "iptables"

# - name: "SECTION | 3.4.4.2.x | Configure iptables IPv6"
#   include_tasks: cis_3.4.4.2.x.yml
#   when:
#   - ( rhel8cis_firewall == "iptables" and rhel8cis_ipv6_required )

# - name: "SECTION | 3.5 | Configure wireless"
#   import_tasks: cis_3.5.yml

# - name: "SECTION | 3.5 | disable IPv6"
#   include_tasks: cis_3.5.yml
#   when:
#   - not rhel8cis_ipv6_required