---

- name: "SECTION | 3.1.x | Configure network devices"
  ansible.builtin.import_tasks:
      file: cis_3.1.x.yml

- name: "SECTION | 3.2.x | Network kernel modules"
  ansible.builtin.import_tasks:
      file: cis_3.2.x.yml

- name: "SECTION | 3.3.x | Network kernel Parameters"
  ansible.builtin.import_tasks:
      file: cis_3.3.x.yml

- name: "SECTION | 3.4.1.x | Configure firewall utility"
  ansible.builtin.import_tasks:
      file: cis_3.4.1.x.yml

- name: "SECTION | 3.4.2.x | Configure firewall rules"
  ansible.builtin.import_tasks:
      file: cis_3.4.2.x.yml
