---

- name: "1.10 | PATCH | Ensure system-wide crypto policy is not legacy"
  shell: |
      update-crypto-policies --set "{{ rhel8cis_crypto_policy }}"
      update-crypto-policies
  notify: change_requires_reboot
  when:
      - rhel8cis_rule_1_10
      - rhel8cis_crypto_policy|string not in system_wide_crypto_policy['stdout']
  tags:
      - level1-server
      - level1-workstation
      - automated
      - no system_is_ec2
      - patch
      - rule_1.10
