---

- name: |
        "SCORED | 1.1.2 | PATCH | Ensure /tmp is configured"
        "SCORED | 1.1.3 | PATCH | Ensure nodev option set on /tmp partition"
        "SCORED | 1.1.4 | PATCH | Ensure nosuid option set on /tmp partition"
        "SCORED | 1.1.5 | PATCH | Ensure noexec option set on /tmp partition"
  mount:
      name: /tmp
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_3 %}noexec,{% endif %}{% if rhel8cis_rule_1_1_4 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_5 %}nosuid{% endif %}
  notify: remount tmp
  loop: "{{ ansible_mounts }}"
  when:
      - item.mount == "/tmp"
      - not rhel8cis_tmp_svc
      - rhel8cis_rule_1_1_2 or
        rhel8cis_rule_1_1_3 or
        rhel8cis_rule_1_1_4 or
        rhel8cis_rule_1_1_5
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - mounts
      - rule_1.1.3
      - rule_1.1.4
      - rule_1.1.5

- name: "SCORED | 1.1.6 | PATCH | Ensure separate partition exists for /var"
  mount:
      name: /var
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
  loop: "{{ ansible_mounts }}"
  when:
      - rhel8cis_rule_1_1_6
      - item.mount == "/var"
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - mounts
      - rule_1.1.6
      - skip_ansible_lint

- name: "SCORED | 1.1.7 | PATCH | Ensure separate partition exists for /var/tmp"
  mount:
      name: /var/tmp
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_10 %}noexec,{% endif %}{% if rhel8cis_rule_1_1_8 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_9 %}nosuid{% endif %}
  loop: "{{ ansible_mounts }}"
  when:
      - rhel8cis_rule_1_1_7
      - item.mount == "/var/tmp"
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - mounts
      - rule_1.1.7
      - skip_ansible_lint

- name: |
          "SCORED | 1.1.8  | PATCH | Ensure nodev option set on /var/tmp partition |
           SCORED | 1.1.9  | PATCH | Ensure nosuid option set on /var/tmp partition |
           SCORED | 1.1.10 | PATCH | Ensure noexec option set on /var/tmp partition"
  mount:
      name: /var/tmp
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_10 %}noexec,{% endif %}{% if rhel8cis_rule_1_1_8 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_9 %}nosuid{% endif %}
  loop: "{{ ansible_mounts }}"
  when:
      - item.mount == "/var/tmp"
      - rhel8cis_rule_1_1_7
      - rhel8cis_rule_1_1_8 or
        rhel8cis_rule_1_1_9 or
        rhel8cis_rule_1_1_10
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - mounts  

- name: "SCORED | 1.1.11 | PATCH | Ensure separate partition exists for /var/log"
  mount:
      name: /var/log
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
  loop: "{{ ansible_mounts }}"
  when:
      - rhel8cis_rule_1_1_11
      - item.mount == "/var/log"
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - mounts
      - rule_1.1.11
      - skip_ansible_lint

- name: "SCORED | 1.1.12 | PATCH | Ensure separate partition exists for /var/log/audit"
  mount:
      name: /var/log/audit
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
  loop: "{{ ansible_mounts }}"
  when:
      - rhel8cis_rule_1_1_12
      - item.mount == "/var/log/audit"
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - mounts
      - rule_1.1.12
      - skip_ansible_lint

- name: |
      "SCORED | 1.1.13 | AUDIT | Ensure separate partition exists for /home"
      "SCORED | 1.1.14 | PATCH | Ensure nodev option set on /home partition"
  mount:
      name: /home
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_14 %}nodev{% endif %}
  loop: "{{ ansible_mounts }}"
  when:
      - item.mount == "/home"
      - rhel8cis_rule_1_1_13 or
        rhel8cis_rule_1_1_14
  tags:
      - level2-server
      - level2-workstation
      - scored
      - audit
      - mounts
      - rule_1.1.13 
      - skip_ansible_lint

- name: |
         "SCORED | 1.1.15 | PATCH | Ensure nodev option set on /dev/shm partition |
          SCORED | 1.1.16 | PATCH | Ensure nosuid option set on /dev/shm partition |
          SCORED | 1.1.17 | PATCH | Ensure noexec option set on /dev/shm partition"
  mount:
      name: /dev/shm
      src: "{{ item.device }}"
      fstype: tmpfs
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_17 %}noexec,{% endif %}{% if rhel8cis_rule_1_1_15 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_16 %}nosuid{% endif %}
  loop: "{{ ansible_mounts }}"
  when:
      - item.mount == "/dev/shm"
      - rhel8cis_rule_1_1_15 or
        rhel8cis_rule_1_1_16 or
        rhel8cis_rule_1_1_17
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - mounts
      - rule_1.1.15
      - rule_1.1.16
      - rule_1.1.17

- name: |
      "NOTSCORED | 1.1.18 | AUDIT | Ensure nodev option set on removable media partitions"
      "NOTSCORED | 1.1.19 | AUDIT | Ensure nosuid option set on removable media partitions"
      "NOTSCORED | 1.1.20 | AUDIT | Ensure noexec option set on removable media partitions"
  debug:
      msg: "--> Not relevant"
  changed_when: false
  when:
      - rhel8cis_rule_1_1_18 or
        rhel8cis_rule_1_1_19 or
        rhel8cis_rule_1_1_20
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - audit
      - mounts
      - rule_1.1.18
      - rule_1.1.19
      - rule_1.1.20

- name: "SCORED | 1.1.21 | PATCH | Ensure sticky bit is set on all world-writable directories"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  changed_when: false
  failed_when: false
  when:
      - rhel8cis_rule_1_1_21
  tags:
      - level1-server
      - level1-workstation
      - patch
      - stickybits
      - permissons
      - rule_1.1.21

- name: "SCORED | 1.1.22 | PATCH | Disable Automounting"
  service:
      name: autofs
      enabled: no
  when:
      - not rhel8cis_allow_autofs
      - "'autofs' in ansible_facts.packages"
      - rhel8cis_rule_1_1_22
  tags:
      - level1-server
      - level2-workstation
      - patch
      - mounts
      - automounting
      - rule_1.1.22

- name: "SCORED | 1.1.23 | PATCH | Disable USB Storage"
  block:
      - name: "SCORED | 1.1.23 | PATCH | Disable USB Storage | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install usb-storage(\\s|$)"
            line: "install usb-storage /bin/true"
            create: yes
      - name: "SCORED | 1.1.23 | PATCH | Disable USB Storage | Edit modprobe config"
        modprobe:
            name: usb-storage
            state: absent
  when:
      - rhel8cis_rule_1_1_23
  tags:
      - level1-server
      - level2-workstation
      - patch
      - mounts
      - removable_storage
      - rule_1.1.23