---

- name: "1.1.5.1 | AUDIT | Ensure separate partition exists for /var/log"
  block:
      - name: "1.1.5.1 | AUDIT | Ensure separate partition exists for /var/log | Absent"
        debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"
        register: var_log_mount_absent
        changed_when: var_log_mount_absent.skipped is undefined
        when:
            - required_mount not in mount_names

      - name: "1.1.5.1 | AUDIT | Ensure separate partition exists for /var/log | Warn Count"
        set_fact:
            control_number: "{{ control_number }} + [ 'rule_1.1.5.1' ]"
            warn_count: "{{ warn_count | int + 1 }}"
        when:
            - required_mount not in mount_names

      - name: "1.1.5.1 | AUDIT | Ensure separate partition exists for /var/log | Present"
        debug:
            msg: "Congratulations: {{ required_mount }} exists."
        register: var_log_mount_present
        when:
            - required_mount in mount_names
  vars:
      required_mount: '/var/log'
  when:
      - rhel8cis_rule_1_1_5_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - mounts
      - rule_1.1.5.1
      - skip_ansible_lint

- name: |
          "1.1.5.2 | PATCH | Ensure nodev option set on /var/log partition"
          "1.1.5.3 | PATCH | Ensure noexec option set on /var/log partition"
          "1.1.5.4 | PATCH | Ensure nosuid option set on /var/log partition"
  mount:
      name: /var/log
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_5_3 %}noexec,{% endif %}{% if rhel8cis_rule_1_1_5_2 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_5_4 %}nosuid{% endif %}
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  notify: change_requires_reboot
  when:
      - var_log_mount_present is defined
      - item.mount == "/var/log"
      - rhel8cis_rule_1_1_5_1  # This is required so the check takes place
      - rhel8cis_rule_1_1_5_2 or
        rhel8cis_rule_1_1_5_3 or
        rhel8cis_rule_1_1_5_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - skip_ansible_lint
      - rule_1.1.5.2
      - rule_1.1.5.3
      - rule_1.1.5.4
