---

- name: "SECTION | 1.1.1.x | Disable unused filesystems"
  import_tasks: cis_1.1.1.x.yml

- name: "SECTION | 1.1.2.x | Configure /tmp"
  import_tasks: cis_1.1.2.x.yml

- name: "SECTION | 1.1.3.x | Configure /var"
  import_tasks: cis_1.1.3.x.yml

- name: "SECTION | 1.1.4.x | Configure /var/tmp"
  import_tasks: cis_1.1.4.x.yml

- name: "SECTION | 1.1.5.x | Configure /var/log"
  import_tasks: cis_1.1.5.x.yml

- name: "SECTION | 1.1.6.x | Configure /var/log/audit"
  import_tasks: cis_1.1.6.x.yml

- name: "SECTION | 1.1.7.x | Configure /home"
  import_tasks: cis_1.1.7.x.yml

- name: "SECTION | 1.1.8.x | Configure /dev/shm"
  import_tasks: cis_1.1.8.x.yml

- name: "SECTION | 1.1.x | Disable various mounting"
  import_tasks: cis_1.1.x.yml

- name: "SECTION | 1.2 | Configure Software Updates"
  import_tasks: cis_1.2.x.yml

- name: "SECTION | 1.3 | Filesystem Integrity Checking"
  import_tasks: cis_1.3.x.yml
  when: rhel8cis_config_aide

- name: "SECTION | 1.4 | Secure Boot Settings"
  import_tasks: cis_1.4.x.yml

- name: "SECTION | 1.5 | Additional Process Hardening"
  import_tasks: cis_1.5.x.yml

- name: "SECTION | 1.6 | Mandatory Access Control"
  import_tasks: cis_1.6.1.x.yml
  when: not rhel8cis_selinux_disable

- name: "SECTION | 1.7 | Command Line Warning Banners"
  import_tasks: cis_1.7.x.yml

- name: "SECTION | 1.8 | Gnome Display Manager"
  import_tasks: cis_1.8.x.yml

- name: "SECTION | 1.9 | Updates and Patches"
  import_tasks: cis_1.9.yml

- name: "SECTION | 1.10 | Crypto policies"
  import_tasks: cis_1.10.yml
  when:
  - not system_is_ec2
