---

- name: "SECTION | 1.1.1.x | Disable unused filesystems"
  ansible.builtin.import_tasks:
      file: cis_1.1.1.x.yml

- name: "SECTION | 1.1.2.1.x | Configure /tmp"
  ansible.builtin.import_tasks:
      file: cis_1.1.2.1.x.yml

- name: "SECTION | 1.1.2.2.x | Configure /dev/shm"
  ansible.builtin.import_tasks:
      file: cis_1.1.2.2.x.yml

- name: "SECTION | 1.1.2.3.x | Configure /home"
  ansible.builtin.import_tasks:
      file: cis_1.1.2.3.x.yml

- name: "SECTION | 1.1.2.4.x | Configure /var"
  ansible.builtin.import_tasks:
      file: cis_1.1.2.4.x.yml

- name: "SECTION | 1.1.2.5.x | Configure /var/tmp"
  ansible.builtin.import_tasks:
      file: cis_1.1.2.5.x.yml

- name: "SECTION | 1.1.2.6.x | Configure /var/log"
  ansible.builtin.import_tasks:
      file: cis_1.1.2.6.x.yml

- name: "SECTION | 1.1.2.7.x | Configure /var/log/audit"
  ansible.builtin.import_tasks:
      file: cis_1.1.2.7.x.yml

- name: "SECTION | 1.2 | DNF and updates"
  ansible.builtin.import_tasks:
      file: cis_1.2.x.yml

- name: "SECTION | 1.3 | Bootloader"
  ansible.builtin.import_tasks:
      file: cis_1.3.x.yml

- name: "SECTION | 1.4 | sysctl kernel"
  ansible.builtin.import_tasks:
      file: cis_1.4.x.yml

- name: "SECTION | 1.5 | SELinux"
  when: not rhel8cis_selinux_disable
  ansible.builtin.import_tasks:
      file: cis_1.5.1.x.yml

- name: "SECTION | 1.6 | Crypto"
  ansible.builtin.import_tasks:
      file: cis_1.6.x.yml

- name: "SECTION | 1.7 | Command Line Warning Banners"
  ansible.builtin.import_tasks:
      file: cis_1.7.x.yml

- name: "SECTION | 1.8 | Gnome Display Manager"
  when: rhel8cis_gui
  ansible.builtin.import_tasks:
      file: cis_1.8.x.yml
