---

- name: "4.2.3 | L1 | PATCH | Ensure permissions on all logfiles are configured"
  command: find /var/log/ -type f -perm /g+wx,o+rwx -exec chmod g-wx,o-rwx "{}" +
  changed_when: false
  failed_when: false
  when:
      - rhel8cis_rule_4_2_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.2.3
