---

- name: "SCORED | 4.1.3 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  template:
      src: audit/rhel8cis_rule_4_1_3.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_3.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_3
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.3

- name: "SCORED | 4.1.4 | PATCH | Ensure login and logout events are collected"
  template:
      src: audit/rhel8cis_rule_4_1_4.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_4.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_4
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.4

- name: "SCORED | 4.1.5 | PATCH | Ensure session initiation information is collected"
  template:
      src: audit/rhel8cis_rule_4_1_5.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_5.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_5
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.5

- name: "SCORED | 4.1.6 | PATCH | Ensure events that modify date and time information are collected"
  template:
      src: audit/rhel8cis_rule_4_1_6.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_6.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_6
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.6

- name: "SCORED | 4.1.7 | PATCH | Ensure events that modify the system's Mandatory Access Controls are collected"
  template:
      src: audit/rhel8cis_rule_4_1_7.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_7.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_7
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.7

- name: "SCORED | 4.1.8 | PATCH | Ensure events that modify the system's network environment are collected"
  template:
      src: audit/rhel8cis_rule_4_1_8.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_8.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_8
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.8

- name: "SCORED | 4.1.9 | PATCH | Ensure discretionary access control permission modification events are collected"
  template:
      src: audit/rhel8cis_rule_4_1_9.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_9.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_9
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.9

- name: "SCORED | 4.1.10 | PATCH | Ensure unsuccessful unauthorized file access attempts are collected"
  template:
      src: audit/rhel8cis_rule_4_1_10.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_10.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_10
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.10

- name: "SCORED | 4.1.11 | PATCH | Ensure events that modify user/group information are collected"
  template:
      src: audit/rhel8cis_rule_4_1_11.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_11.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_11
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.11

- name: "SCORED | 4.1.12 | PATCH | Ensure successful file system mounts are collected"
  block:
      - name: "SCORED | 4.1.12 | PATCH | Ensure successful file system mounts are collected"
        shell: for i in  $(df | grep '^/dev' | awk '{ print $NF }'); do find $i -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null; done
        changed_when: false
        failed_when: false
        register: priv_procs

      - name: "SCORED | 4.1.12 | PATCH | Ensure successful file system mounts are collected"
        template:
            src: audit/rhel8cis_rule_4_1_12.rules.j2
            dest: /etc/audit/rules.d/rhel8cis_rule_4_1_12.rules
            owner: root
            group: root
            mode: 0600
        notify: restart auditd
  when:
      - rhel8cis_rule_4_1_12
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.12

- name: "SCORED | 4.1.13 | PATCH | Ensure use of privileged commands is collected"
  template:
      src: audit/rhel8cis_rule_4_1_13.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_13.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_13
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.13

- name: "SCORED | 4.1.14 | PATCH | Ensure file deletion events by users are collected"
  template:
      src: audit/rhel8cis_rule_4_1_14.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_14.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_14
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.14

- name: "SCORED | 4.1.15 | PATCH | Ensure kernel module loading and unloading is collected"
  template:
      src: audit/rhel8cis_rule_4_1_15.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_15.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_15
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.15

- name: "SCORED | 4.1.16 | PATCH | Ensure system administrator actions (sudolog) are collected"
  template:
      src: audit/rhel8cis_rule_4_1_16.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_16.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_16
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.16

- name: "SCORED | 4.1.17 | PATCH | Ensure the audit configuration is immutable"
  template:
      src: audit/rhel8cis_rule_4_1_17.rules.j2
      dest: /etc/audit/rules.d/rhel8cis_rule_4_1_17.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - rhel8cis_rule_4_1_17
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.17