---

- name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
  block:
      - name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured | Get logrotate settings"
        find:
            paths: /etc/logrotate.d/
        register: log_rotates

      - name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
        replace:
            path: "{{ item.path }}"
            regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
            replace: "\\1{{ rhel8cis_logrotate }}"
        with_items:
        - "{{ log_rotates.files }}"
        - { path: "/etc/logrotate.conf" }
  when:
      - rhel8cis_rule_4_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.3