---

- name: "SECTION | 4.1| Configure System Accounting (auditd)"
  include_tasks: cis_4.1.1.x.yml

- name: "SECTION | 4.1.2.x| Configure Data Retention"
  include_tasks: cis_4.1.2.x.yml

- name: "SECTION | 4.1.x| Auditd rules"
  include_tasks: cis_4.1.x.yml

- name: "SECTION | 4.2.x| Configure Logging"
  import_tasks: cis_4.2.1.x.yml
  when: rhel8cis_syslog == 'rsyslog'

- name: "SECTION | 4.2.2.x| Configure journald"
  include_tasks: cis_4.2.2.x.yml

- name: "SECTION | 4.2.3 | Configure logile perms"
  include_tasks: cis_4.2.3.yml

- name: "SECTION | 4.3 | Configure logrotate"
  include_tasks: cis_4.3.yml